apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-frontend.fullname" . }}
  labels:
    app: {{ include "react-frontend.name" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "react-frontend.name" . }}
