name: React Frontend CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-2
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160071257600:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install dependencies
        working-directory: ./react-frontend/app
        run: |
          npm ci

      - name: Build Docker image
        working-directory: ./react-frontend/app
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/react-frontend:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/react-frontend:${{ env.IMAGE_TAG }}

      - name: Update Helm values with image tag
        working-directory: ./react-frontend/chart
        run: |
          sed -i "s|tag:.*|tag: \"${{ env.IMAGE_TAG }}\"|" values.yaml
          sed -i "s|repository:.*|repository: \"${{ steps.login-ecr.outputs.registry }}/react-frontend\"|" values.yaml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name np-eks-fargate

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Add AWS EKS Helm repo
        run: helm repo add eks https://aws.github.io/eks-charts && helm repo update

      - name: Install AWS Load Balancer Controller CRDs
        run: |
          kubectl apply -f https://github.com/aws/eks-charts/raw/master/stable/aws-load-balancer-controller/crds/crds.yaml        

      - name: Install jq
        run: |
          sudo apt install -y jq
          jq --version

      - name: Get VPC ID from Terraform
        id: get-vpc-id
        run: |
          echo "VPC_ID=$(aws ec2 describe-vpcs --filters Name=tag:Name,Values=np-eks-vpc | jq -r '.Vpcs | .[] | .VpcId')" >> $GITHUB_ENV

      - name: Install/Upgrade AWS Load Balancer Controller
        run: |
          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
            --namespace kube-system \
            --set enableServiceMutatorWebhook=false \
            --set clusterName=np-eks-fargate \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller \
            --set region=ap-southeast-2 \
            --set vpcId=$VPC_ID \
            --set image.tag="v2.7.1"
  


      - name: Deploy to EKS with Helm
        working-directory: ./react-frontend/chart
        run: |
          helm upgrade --install react-frontend . --namespace default --create-namespace
