name: Terraform CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy resources instead of apply?'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-eks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tfenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH

      - name: Install and use Terraform with tfenv
        run: |
          tfenv install
          tfenv use

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160071257600:role/github-actions-terraform
          aws-region: ap-southeast-2

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        run: terraform test

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply or Destroy
        run: |
          if [[ "${{ github.event.inputs.destroy }}" == "true" ]]; then
            echo "Running terraform destroy..."
            terraform destroy -auto-approve
          else
            echo "Running terraform apply..."
            terraform apply -auto-approve
          fi

      # --- Kubernetes Layer ---
      - name: Export Kubernetes Token
        id: export-kube-token
        run: |
          CLUSTER_NAME="np-eks-fargate"
          AWS_REGION="ap-southeast-2"
          export TF_VAR_kubernetes_token=$(aws eks get-token --cluster-name "$CLUSTER_NAME" --region "$AWS_REGION" --query 'status.token' --output text)
          echo "TF_VAR_kubernetes_token=$TF_VAR_kubernetes_token" >> $GITHUB_ENV

      - name: Terraform Init (k8s)
        run: terraform init -reconfigure
        working-directory: ./terraform-k8s

      - name: Terraform Plan (k8s)
        run: terraform plan
        working-directory: ./terraform-k8s

      - name: Terraform Apply (k8s)
        run: terraform apply -auto-approve
        working-directory: ./terraform-k8s
