name: Terraform K8s Layer

on:
  repository_dispatch:
    types: [apply-k8s]
  workflow_dispatch:

jobs:
  terraform-k8s:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tfenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH

      - name: Install and use Terraform with tfenv
        run: |
          tfenv install
          tfenv use

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160071257600:role/github-actions-terraform
          aws-region: ap-southeast-2

      - name: Export Kubernetes Token
        id: export-kube-token
        run: |
          CLUSTER_NAME="np-eks-fargate"
          AWS_REGION="ap-southeast-2"
          export TF_VAR_kubernetes_token=$(aws eks get-token --cluster-name "$CLUSTER_NAME" --region "$AWS_REGION" --query 'status.token' --output text)
          echo "TF_VAR_kubernetes_token=$TF_VAR_kubernetes_token" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
