name: Terraform CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy resources instead of apply?'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ROLE_TO_ASSUME: arn:aws:iam::160071257600:role/github-actions-terraform
      AWS_REGION: ap-southeast-2
      TF_WORKDIR: ./terraform-eks
    defaults:
      run:
        working-directory: ${{ env.TF_WORKDIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tfenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH

      - name: Install and use Terraform with tfenv
        run: |
          tfenv install
          tfenv use

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: TFLint
        run: tflint --recursive

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        run: terraform test

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply or Destroy
        run: |
          if [[ "${{ github.event.inputs.destroy }}" == "true" ]]; then
            echo "Running terraform destroy..."
            terraform destroy -auto-approve
          else
            echo "Running terraform apply..."
            terraform apply -auto-approve
          fi

